name: Deploy to Digital Ocean

on:
  push:
    branches:
      - main

jobs:
  build_and_push:
    name: Build, Push, and Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v2

    - name: Build container image
      run: docker compose -f docker-compose.yml build

    - name: Install `doctl`
      uses: digitalocean/action-doctl@v2
      with:
        token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

    - name: Log in to Digital Ocean Container Registry
      run: doctl registry login --expiry-seconds 600

    - name: Push image to Digital Ocean Container Registry
      run: docker compose -f docker-compose.yml push

    - name: Deploy via SSH
      uses: appleboy/ssh-action@0.1.5
      with:
        host: ${{ secrets.DIGITALOCEAN_HOST }}
        username: ${{ secrets.DIGITALOCEAN_USERNAME }}
        password: ${{ secrets.DIGITALOCEAN_PASSWORD }}
        port: ${{ secrets.DIGITALOCEAN_PORT }}
        script: |
          cd /root/app
          ls